### ISSUE TITLE
Doesn't work with some scripts

### ISSUE THREAD

**Issue by afk11** [kallewoof/btcdeb#13]
Hi,

I'm really interested in the MASTify stuff, as I have been implementing some of these routines for a while now! 

It looks like it fails on this script from BIP114: https://github.com/bitcoin/bips/blob/master/bip-0114.mediawiki#hashed-time-lock-contract - returning "ELSE without IF". 

I got to look at it briefly, and it ran into the error after processing the second OP_ENDIF. I should find some time again soon to look at it, wanted to post it in case the script helps you also.
```
OP_HASH160 OP_DUP 0x36e11d89e9138321fe57037752f0f5b33543735c OP_EQUAL 
OP_IF 
    0x00a41f OP_CHECKSEQUENCEVERIFY OP_2DROP 
    0x02d39621fe21a7074c7b10c6791c88a8c0a5c1253033e68d703f4f298e335fd649 
OP_ELSE 
    0x442328b49e3071bddbafc0f8b7b6aad0b7dbcc63 OP_EQUAL 
    OP_NOTIF
        0x36e0ed5a OP_CHECKLOCKTIMEVERIFY OP_DROP 
    OP_ENDIF 
    0x031d3363f3df80affe482fcb52a620052909d874aecd469f28995ff2468bbd48e8 
OP_ENDIF 
OP_CHECKSIG
```

**Comment by kallewoof** [comment]
Cool! Will look into why that would break. It may be that it gets confused over `OP_NOTIF`, but pretty sure I covered that...

**Comment by kallewoof** [comment]
Apparently I was not handling nested if cases correctly. Specifically, the "inactive path" needs to add another "disabled" to the active vector. Would you mind trying on latest master and seeing if it looks okay?

**Comment by afk11** [comment]
Great, it seems to work for that script now! Nice one!

One thing, I noticed the second and third path both show as `path: 1`. Is that intentional?

**Comment by kallewoof** [comment]
Mark Friedenbach explained that once. That path is actually the path in the merkle tree, not the index of the option, so you don't get "0, 1, 2, 3, ..." necessarily.

**Comment by afk11** [comment]
OK, that makes more sense. Many thanks!
