### ISSUE TITLE
Issue running transaction verification example in README

### ISSUE THREAD

**Issue by afk11** [kallewoof/btcdeb#17]
I checked transaction verification example today, but it doesn't work anymore. Seems when the docs were added (1d6c065bf47631d9f8f2b9b6061d2c494884c5a5) it worked well, but it doesn't currently convert the ws to a sequence of ops.

Will dig into this a bit more later, just posting here for now :)

Last working commit (before the rebase) 4578842fe0e16032b118b85570d684cda1e80b4f

**Comment by kallewoof** [comment]
Good catch! It definitely is not working correctly right now.

**Comment by sabran125** [comment]
thanks you so much

**Comment by kallewoof** [comment]
Fixed in 9ff8e00897c46e423309eba704c045e24a0ff535

**Comment by afk11** [comment]
Awesome, thanks for looking into it!
