### ISSUE TITLE
libtool dependency

### ISSUE THREAD

**Issue by MangoSalad** [kallewoof/btcdeb#18]
On ubuntu ./autoconfigure.sh fails without libtool.

`Makefile.am:3: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:3:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:3:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:3:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:3:   its definition is in aclocal's search path.
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
autoreconf: automake failed with exit status: 1`

Fixed with `apt-get install libtool`

**Comment by kallewoof** [comment]
Thanks! Updating the README file.
