### ISSUE TITLE
Ubuntu Linux installation failed with Makefile.am:3 errors

### ISSUE THREAD

**Issue by maxcado** [kallewoof/btcdeb#24]

**Comment by maxcado** [comment]
Hello, trying to check out this script debugger software that looks very useful. However, having a bit of problem installing on Ubuntu Linux machine.  Right at the point of ./autogen.sh I get the following:

configure.ac:20: installing 'build-aux/compile'
configure.ac:20: installing 'build-aux/config.guess'
configure.ac:20: instaling 'build-aux/config.sub'
configure.ac:20: installing 'build-aux/install-sh'
configure.ac:20: installing 'build-aux/missing'
Makefile.am:3: error: Libtool library used but 'LIBTOOL is undefined
Makefile.am:3:  The usaul way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:3: to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:3: If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:3: its definition is in aclocal's search path.
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
autoreconf: automake failed with exit status: 1

Any suggestions on how to get this installed properly?

**Comment by kallewoof** [comment]
Try `apt install libtool`?

**Comment by maxcado** [comment]
libtool is installed already. I also installed the following:
$ sudo apt-get install autoconf
$ sudo apt-get install g++
$ sudo apt-get install pkg-config
$ sudo apt-get install make
But what was missing was:
 sudo apt-get install libreadline-dev
After doing that, then:
$ cd btcdeb
$ ./autogen.sh
$ ./configure
$ make
$ sudo make install
I got it installed. What let me know that was:
$ which btcdeb
/usr/local/bin/btcdeb

**Comment by kallewoof** [comment]
Odd that your error was about libtool and not libreadline, but glad you found it. Closing this issue then :)
