### ISSUE TITLE
Boost dependency

### ISSUE THREAD

**Issue by danrobinson** [kallewoof/btcdeb#3]
On Mac OS X, `make` failed with the following output:

```
  CXX      btcdeb-btcdeb.o
  CXX      libbitcoin_a-base58.o
base58.cpp:13:10: fatal error: 'boost/variant/apply_visitor.hpp' file not found
#include <boost/variant/apply_visitor.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [libbitcoin_a-base58.o] Error 1
make: *** [all-recursive] Error 1
```

Fixed after running `brew install boost`.

**Comment by kallewoof** [comment]
Of course! Thanks for the heads up. Added a dependencies list with this in it to the readme.

**Comment by kallewoof** [comment]
A bit late, but I realized afterwards that it's not actually using boost. I removed those `#include`s and it compiles now without it.
