### ISSUE TITLE
Mock signatures

### ISSUE THREAD

**Issue by kanzure** [kallewoof/btcdeb#32]
It would be helpful if mock keys and signatures could be provided. This would let the user step through a bitcoin script template without having to create keys, signatures or transactions.

The input could be something like a dictionary of public keys and which signatures should be assumed to correspond to which public keys.

**Comment by kallewoof** [comment]
I believe I got this in place. Let me know if I missed something.

**Comment by kallewoof** [comment]
I already realized I didn't actually patch the CHECKMULTISIG operator..

**Comment by kallewoof** [comment]
Patched.
