### ISSUE TITLE
had to install automake for mac catalina

### ISSUE THREAD

**Issue by rednaxus** [kallewoof/btcdeb#36]
otherwise getting:

Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory

i.e. brew automake

**Comment by kallewoof** [comment]
Thanks! I added `autoconf` to the brew install list on the README file.
