### ISSUE TITLE
Can we get the "pseudo-opcodes" back?

### ISSUE THREAD

**Issue by gwillen** [kallewoof/btcdeb#46]
It appears that btcc used to support some "pseudo-opcodes" that Bitcoin Core uses (used?) internally as placeholders, but are not valid in real Script. They were removed here:

https://github.com/kallewoof/btcdeb/commit/3a6e3ef2bd6fbbe6076f0bfb1b9729823a74cde3#diff-642cf6d9959058688f4b8d7c848e0605L169

It looks like we (Blockstream) have an internal tool that depends on btcc understanding "OP_PUBKEY" to mean "0xfe", which are are using for our own script templating purposes. The tool can be changed, so I don't really need that specific mapping to exist, but I need some way to insert "0xfe" directly into the raw script as a placeholder byte, even though it is not a valid opcode.

If you're willing to restore support for OP_PUBKEY, or add another way to insert unquoted bytes, I would very much appreciate it!

(Also, you may want to emit some kind of warning if you parse a "string" that begins with "OP_", which suggests that it was meant to be parsed as an opcode, but with a typo or something. Right now it will just get inserted into the script silently as a data push of the string bytes.)

**Comment by kallewoof** [comment]
@gwillen Mind trying #47 out?

**Comment by kallewoof** [comment]
Looking closer, it indeed looks like Bitcoin Core deprecated these templating opcodes recently, which is why they also disappeared here.

Perhaps using #48 is the best approach after all, since I don't want to deviate from Bitcoin Core if I can help it.

**Comment by gwillen** [comment]
Thanks, I tried out #48 and it looks great. I'm not surprised that indeed Core is no longer using these pseudo-ops, and I understand wanting to follow Core on this. The thing we're doing with them is kind of weird and I think the escape hatch of OP_xNN is a good solution.

**Comment by kallewoof** [comment]
Cool! Closing. Lemme know if there's anything you needed that I missed.
